subcomponents:
  elasticsearch-fluentd-kibana:
    config:
    subcomponents:
      elasticsearch:
        config:
          master:
            persistence:
              storageClass: "managed-premium"
          data:
            persistence:
              storageClass: "managed-premium"
  prometheus-grafana:
    config:
    subcomponents:
      grafana:
        config:
          persistence:
            storageClassName: "managed-premium"
      prometheus:
        config:
          alertmanager:
            persistentVolume:
              storageClass: "managed-premium"
          server:
            persistentVolume:
              storageClass: "managed-premium"
